<a href="https://colab.research.google.com/github/aquibjaved/Bits_and_Pieces_DL/blob/main/understanding_s4_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
## S4 models are used for long sequences,The goal of these kind of models are Efficient modeling for long sequences.
## Applications: Really long sequence matching like, DNA matching, Chat application for example you can talk years.
## Following the tutorial: https://srush.github.io/annotated-s4/#:~:text=The%20Structured%20State%20Space%20for,tens%20of%20thousands%20of%20steps.
## Most of the code is written in jax, we'll try to understand and re-write in python.



# What are state space models, in simple terms a model which remembers the state which is useful to it. So, mathematically they say, in simple terms
# It maps the 1D signal to N Dimensional latent space before projecting to 1D signal.
# Transforming a one-dimensional input signal into a multi-dimensional latent state before converting it back to a one-dimensional output.
# Imagine you have a simple melody (the input signal) that you play on a piano. This melody is then arranged for an orchestra (the N-dimensional latent state),
# where each instrument adds complexity and richness to the original melody. Finally, the orchestra's performance is recorded with a single microphone,
# producing a new, enriched version of the melody (the output signal). This process enriches the original input by exploring its possibilities in a higher-dimensional
# space before condensing it back into a form that's similar to the original input but more complex and nuanced

In [6]:
import numpy as np

In [8]:
"""
SSM Block where u(t) is the signal @ time t, x(t) is the N Dimensional latest space
x′(t) = Ax(t) + Bu(t)
y(t) = Cx(t) + Du(t)


Our goal is to simply use the SSM as a black-box representation in a deep sequence
model, where are parameters learned by gradient descent.
"""
def random_SSM(N):
    A = np.random.uniform(low=0.0, high=1.0, size=(N, N))
    B = np.random.uniform(low=0.0, high=1.0, size=(N, 1))
    C = np.random.uniform(low=0.0, high=1.0, size=(1, N))
    return A, B, C


In [9]:
random_SSM(N=5)

(array([[0.05301059, 0.34368207, 0.76692829, 0.25081378, 0.13667601],
        [0.90848259, 0.90015137, 0.95680001, 0.72836906, 0.73062383],
        [0.31095065, 0.43983436, 0.56548702, 0.84067153, 0.62415758],
        [0.22697586, 0.54753701, 0.10032978, 0.73676666, 0.12468651],
        [0.58219704, 0.64283194, 0.60756392, 0.60586405, 0.29696921]]),
 array([[0.17013911],
        [0.152374  ],
        [0.98210037],
        [0.63522387],
        [0.07065036]]),
 array([[0.30956843, 0.71549923, 0.79330042, 0.40261376, 0.58121063]]))